spring.application.name=assignment
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=reservation-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.datasource.url=jdbc:h2:mem:hoteldb
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.hotel.assignment.dto
spring.kafka.consumer.properties.spring.json.value.default.type=com.hotel.assignment.dto.PaymentUpdateEvent
payment-service.base-url=http://localhost:8081
payment-service.connectTimeout=3s
payment-service.readTimeout=5s